theme: jekyll-theme-architect

title: [metro-stax-ex]
description: [Extended StAX API]

# sidebar links url
links:
  source: https://github.com/javaee/metro-stax-ex
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

